sudo: required

env:
  global:
    - CC_TEST_REPORTER_ID=910515cd7273349a55fdee48d849f5d53a2cabe16c23c74747d1213157512bbc

language: python

python:
  - "3.6"

services:
  - docker

branches:
  only:
  - master
  - dev
  - qa

before_install:
  - if [ "$TRAVIS_BRANCH" == "master"  ]; 
    then export TAG=latest; 
    else export TAG=$TRAVIS_BRANCH; fi

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - docker pull alpine:3.7
  - travis_wait 10 docker pull ramrodpcp/database-brain:$TAG;
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_script:
  - pytest --cov --cov-config .coveragerc --cov-report xml ./test
  - ./cc-test-reporter after-build -t coverage.py --exit-code 0

script:
  - docker build -t ramrodpcp/interpreter-plugin:$TAG .
  - docker network create test
  - docker run -d --name rethinkdb --network test -p 28015:28015  -e "STAGE=DEV" -e "LOGLEVEL=DEBUG" ramrodpcp/database-brain:$TAG
  - docker run -d --name Harness --network test -p 5000:5000 -e "STAGE=DEV" -e "LOGLEVEL=DEBUG" -e "PLUGIN=Harness" -e "PORT=5000" ramrodpcp/backend-interpreter:$TAG
  - sleep 30
  - docker ps -a
  # print the logs
  - docker logs Harness
  - docker logs rethinkdb
  - docker stop Harness
  - docker stop rethinkdb

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]];
    then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false"  ]];
    then docker push ramrodpcp/interpreter-plugin:$TAG; fi

notifications:
  slack: ramrod-project:GDF82rRYDg3KSekrT3GA24qO