sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - git clone https://github.com/ramrod-project/backend-interpreter.git

install:
  - pip install -r plugin_interpreter/requirements.txt

before_script:
  - pytest plugin_interpreter/test

script:
  - docker build -t ramrodpcp/backend-interpreter .
  - docker run -d --rm --name controller -e "STAGE=DEV" -e "LOGLEVEL=DEBUG" -v /var/run/docker.sock:/var/run/docker.sock ramrodpcp/backend-interpreter
  # This will eventually be for more integration testing
  - sleep 30
  - containers=$(docker ps | grep -vi "\(CONTAINER\|controller\|rethinkdb\)" | awk '{print $1}')
  # print the logs for each plugin
  - for c in "${containers[@]}"; do docker logs $c; done 
  - docker stop controller

after_success:
  - if [ "$TRAVIS_BRANCH" = "qa"  ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [ "$TRAVIS_BRANCH" = "qa"  ]; then docker push ramrodpcp/backend-interpreter; fi

notifications:
  slack: ramrod-project:GDF82rRYDg3KSekrT3GA24qO