FROM stefanscherer/python-windows:nano

RUN NET USER appuser /add
RUN NET LOCALGROUP ADMINISTRATORS /add appuser
RUN NET USER appuser /expires:never
RUN NET ACCOUNTS /MaxPWAge:unlimited

USER appuser

WORKDIR c:\\Users\\appuser\\approot

COPY requirements.txt .

RUN pip.exe install -r requirements.txt

COPY . .

HEALTHCHECK --interval=2s --start-period=10s --retries=3 CMD powershell.exe ./healthcheck.ps1

EXPOSE 5000

ENTRYPOINT python.exe server.py "${PLUGIN}"
