FROM ramrodpcp-wine-base:latest

WORKDIR /tmp
COPY ./requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /opt/app-root/src
COPY . .

HEALTHCHECK --interval=2s --start-period=10s --retries=3 CMD /bin/sh ./healthcheck.sh

ENTRYPOINT python3 server.py "${PLUGIN}"